---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    app: refractr
  name: ingress-nginx
  namespace: refractr-prod
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.2.0
  interval: 1m0s
  releaseName: refractr-ingress-nginx
  values:
    controller:
      admissionWebhooks:
        enable: false
      autoscaling:
        enabled: true
        maxReplicas: 20
        minReplicas: 5
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      config:
        hsts: "false"
        http-redirect-code: "301"
        proxy-real-ip-cidr: 0.0.0.0/0
        ssl-ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA
        ssl-protocols: TLSv1 TLSv1.1 TLSv1.2 TLSv1.3
        use-forwarded-headers: "true"
        use-proxy-protocol: "false"
      enableCustomResources: false
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx-refractr-prod
        default: false
        enabled: true
        name: ingress-nginx-refractr-prod
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      resources:
        limits:
          cpu: 512m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi
      scope:
        enabled: true
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: prod.mozilla-redirects.xyz,prod.refractr.mozit.cloud
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=prod
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0e9eb2d9f63a68ab8,eipalloc-0f4a591198b52e017,eipalloc-06d4150517deeeef7
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
        externalTrafficPolicy: Local
    rbac:
      create: true
      scope: true
