# This used to be in a helm chart but with every helm chart update
# of refractr it causes it to create a new release which recreates the load balancer
# so moving this here to mitigate that
#
# NOTE: Decide if we want this in terraform instead, I can see how this should be in terraform
#       but since its part of the app it should live as a helmrelease
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: refractr-prod
  labels:
    app: refractr
spec:
  releaseName: refractr-ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: "3.33.0"
  values:
    controller:
      useIngressClassOnly: true
      enableCustomResources: false
      autoscaling:
        enabled: true
        minReplicas: 5
        maxReplicas: 20
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 512m
          memory: 1Gi
      admissionWebhooks:
        enable: false
      scope:
        enabled: true
      config:
        use-proxy-protocol: "false"
        use-forwarded-headers: "true"
        # restrict this to the IP addresses of ELB
        proxy-real-ip-cidr: "0.0.0.0/0"
        # HSTS disable here, to be picked up by refractr during redirect
        hsts: "false"
        # SE-3010 Prefer 301 instead of 308 as older browsers do not support 308
        http-redirect-code: "301"
      service:
        externalTrafficPolicy: "Local"
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=prod"
          # not really well documented except for this here:
          # https://github.com/kubernetes/kubernetes/issues/63959
          service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-0e9eb2d9f63a68ab8,eipalloc-0f4a591198b52e017,eipalloc-06d4150517deeeef7"
          external-dns.alpha.kubernetes.io/hostname: "prod.mozilla-redirects.xyz,prod.refractr.mozit.cloud"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "false"
            prometheus.io/port: "10254"
    rbac:
      create: true
      scope: true
