---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    app: moderator
  name: ingress-nginx
  namespace: moderator-prod
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 3.33.0
  interval: 1m0s
  releaseName: moderator-ingress-nginx
  values:
    controller:
      admissionWebhooks:
        enable: false
      autoscaling:
        enabled: true
        maxReplicas: 4
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      config:
        compute-full-forwarded-for: "true"
        enable-real-ip: "true"
        proxy-real-ip-cidr: 172.16.0.0/16
        use-forwarded-headers: "true"
        use-proxy-protocol: "false"
      enableCustomResources: false
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      scope:
        enabled: true
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: moderator.prod.mozit.cloud,moderator.mozilla.org
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=prod
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
        externalTrafficPolicy: Local
      useIngressClassOnly: true
    rbac:
      create: true
      scope: true
