---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: refractr
  namespace: flux-system

spec:
  image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/refractr
  interval: 1m0s
  secretRef:
    name: ecr-credentials
