---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pastebin
  namespace: pastebin-prod
  labels:
    app: pastebin
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(v[0-9]+.[0-9]+.[0-9]+)$
spec:
  releaseName: pastebin
  chart:
    repository: https://mozilla-it.github.io/helm-charts/
    name: pastebin
    version: "0.2.2"
  values:
    configMap:
      data:
        DB_PORT: "3306"
        DPASTE_BASE_DOMAIN: "paste.mozilla.org"
        VAL: "5"
    deployment:
      port: "8000"
      replicaCount: "1"
    externalSecrets:
      enabled: true
      name: pastebin
      store: secretsmanager-secretstore
      secrets:
      - remoteRef:
          key: /prod/pastebin/envvar
          property: DB_HOST
        secretKey: database_host
      - remoteRef:
          key: /prod/pastebin/envvar
          property: DB_NAME
        secretKey: database_name
      - remoteRef:
          key: /prod/pastebin/envvar
          property: DB_PASS
        secretKey: database_password
      - remoteRef:
          key: /prod/pastebin/envvar
          property: DB_USER
        secretKey: database_user
      - remoteRef:
          key: /prod/pastebin/envvar
          property: SESSION_KEY
        secretKey: session_key
    image:
      pullPolicy: Always
      repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/pastebin
      tag: v3.5.8
    imagePullSecrets:
      - name: dockerhub-credentials
    ingress:
      hosts:
      - host: paste.prod.mozit.cloud
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: pastebin
          servicePort: 80
      - host: paste.mozilla.org
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: pastebin
          servicePort: 80
      - host: pastebin.mozilla.org
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: pastebin
          servicePort: 80
      le:
        name: prod
      name: pastebin
      tls:
      - hosts:
        - paste.mozilla.org
        secretName: cert-paste-mozilla-org
      - hosts:
        - pastebin.mozilla.org
        secretName: cert-pastebin-mozilla-org
      - hosts:
        - paste.prod.mozit.cloud
        secretName: cert-paste-prod-mozit-cloud
