---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: moderator
  namespace: moderator-prod
  labels:
    app: moderator
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(v[0-9]+.[0-9]+.[0-9]+)$
spec:
  releaseName: moderator
  chart:
    repository: https://mozilla-it.github.io/helm-charts/
    name: mozmoderator
    version: "0.2.1"
  values:
    configMap:
      data:
        ALLOWED_HOSTS: moderator.prod.mozit.cloud,moderator.mozilla.org
        ANON_ALWAYS: true
        AWS_DEFAULT_REGION: us-west-2
        FROM_NOREPLY: Mozilla Moderator <no-reply@moderator.mozilla.org>
        OIDC_OP_AUTHORIZATION_ENDPOINT: https://auth.mozilla.auth0.com/authorize
        OIDC_OP_DOMAIN: auth.mozilla.auth0.com
        OIDC_OP_JWKS_ENDPOINT: https://auth.mozilla.auth0.com/.well-known/jwks.json
        OIDC_OP_TOKEN_ENDPOINT: https://auth.mozilla.auth0.com/oauth/token
        OIDC_OP_USER_ENDPOINT: https://auth.mozilla.auth0.com/userinfo
        OIDC_RP_SIGN_ALGO: RS256
        SESSION_COOKIE_SECURE: true
        SITE_URL: https://moderator.mozilla.org
    deployment:
      port: "8000"
      replicaCount: "1"
    externalSecrets:
      enabled: true
      name: moderator
      secrets:
        - key: /prod/moderator/envvar
          name: AWS_ACCESS_KEY_ID
          property: AWS_ACCESS_KEY_ID
        - key: /prod/moderator/envvar
          name: AWS_SECRET_ACCESS_KEY
          property: AWS_SECRET_ACCESS_KEY
        - key: /prod/moderator/envvar
          name: DATABASE_URL
          property: DATABASE_URL
        - key: /prod/moderator/envvar
          name: OIDC_RP_CLIENT_ID
          property: OIDC_RP_CLIENT_ID
        - key: /prod/moderator/envvar
          name: OIDC_RP_CLIENT_SECRET
          property: OIDC_RP_CLIENT_SECRET
        - key: /prod/moderator/envvar
          name: SECRET_KEY
          property: SECRET_KEY
        - key: /prod/moderator/envvar
          name: SENTRY_DSN
          property: SENTRY_DSN
    image:
      pullPolicy: Always
      repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/moderator
      tag: v0.1.0
    ingress:
      hosts:
        - host: moderator.prod.mozit.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific
              serviceName: moderator
              servicePort: 80
        - host: moderator.mozilla.org
          paths:
            - path: /
              pathType: ImplementationSpecific
              serviceName: moderator
              servicePort: 80
      le:
        name: prod
      name: moderator
      tls:
        - hosts:
            - moderator.mozilla.org
          secretName: cert-moderator-mozilla-org
        - hosts:
            - moderator.prod.mozit.cloud
          secretName: cert-moderator-prod-mozit-cloud
